### ISSUE TITLE
API: on_destroy errors out when called on a connection_type instantiated by mod

### ISSUE THREAD

**Issue by msu320** [MagmaMcFry/Factorissimo#12]
Made an API template mod for factorissimo (see attached file). tried to do the standard actions and came across this error when removing a connection:

```
Error while running event on_tick (ID 0)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
    [C]: in function 'call'
    __Factorissimo__/connections.lua:114: in function <__Factorissimo__/connections.lua:113>
    (...tail calls...)
    __Factorissimo__/connections.lua:34: in function 'update_pending_connections'
    __Factorissimo__/control.lua:351: in function <__Factorissimo__/control.lua:341>
```

[factorissimo-api-template_0.0.1.zip](https://github.com/MagmaMcFry/Factorissimo/files/441007/factorissimo-api-template_0.0.1.zip)

**Comment by msu320** [comment]
I smell factorio bug

**Comment by MagmaMcFry** [comment]
I'm wondering why you copied Factorissimo's API code to your own mod, it isn't necessary at all. All you need to write in your own mod is the (commented) code detailed in the "HOW TO USE THIS API" comment (connections.lua, lines 84 to 99). In fact, overriding the "factorissimo_connections" API may just have broken everything, because you shouldn't do that.

About the "API call when LuaEntity was invalid": That's exactly what it says on the tin. Somewhere a LuaEntity was modified after it was removed. The (...tail calls...) seem the important part of this error log. What exactly did you do, and did you change any part of my code?

**Comment by msu320** [comment]
copying connections.lua was accidental, and it isn't referenced by control.lua.

control.lua is lines 132 to 281 of your mod's connections.lua code copied in from your mod's connections.lua

**Comment by MagmaMcFry** [comment]
Then I'd like detailed instructions to reproduce the error, please.

**Comment by msu320** [comment]
two ways to reproduce that i've tried (using 0.2.0):

method one:
- add factorissimo-api-template to mod folder.
- run game and load an existing save
- remove outside connected belt. 

method two, testing the potential that overriding existing data is the issue:
- comment out everything after line 132 in connections.lua
- add factorissimo-api-template to mod folder.
- run game and create a new save
- cheat in factory/belts and setup a quick test factory.
- verify that items move inside-outside and vice versa on the belt connections to make sure the interface added by the addon mod works.
- remove outside connected belt.

I forgot that newer versions allowed inside belt connections to be removed now and haven't tested those yet.
