### ISSUE TITLE
Not really an issue yet, but will be with .15

### ISSUE THREAD

**Issue by agentronin316** [MagmaMcFry/Factorissimo#18]
I am inclined to assume you are already aware, but we all know what happens when someone assumes.

According to the Friday facts a couple weeks ago, .15 will start consolidating damaged items into single stacks, with potential to reduce the total number of items.

This looks like it will break the damage abuse you're using to store factory info.

**Comment by Rseding91** [comment]
It hasn't happened yet even in 0.15 (unsure if it will - it was mentioned but nobody has done it).

**Comment by MagmaMcFry** [comment]
Actually I rewrote the factory system for Factorissimo 2 to make it more reliable and mod-compatible. Instead of messing with the damage value, I store item data *directly in the item type*, by having 50 hardcoded separate item and recipe prototypes per factory building. One prototype is for newly crafted factory items and active factory buildings, the others are used so inactive and collected factory buildings can have a unique item type each. Obviously there's the issue that this prevents you from collecting (or marking for destruction) more than 50 factory buildings of the same type at once, but it's still more tolerable than a hard limit on total factories.

This solves the restacking problem, and it also helps with mod compatibility, since the item type and count are the only thing mods can see when they use API methods returning SimpleItemStacks or content tables (in fact, Factorissimo 1 is secretly fundamentally incompatible with *itself*, since it wipes factory data when a factory building item goes through a belt port because there's no way to get LuaItemStacks directly from transport belts).

**Comment by Rseding91** [comment]
@MagmaMcFry 0.15 adds a new item type that can store a mapping of string -> lua basic type (string, table, number) and 0.15 also adds support for reading LuaItemStack off belts.
