### ISSUE TITLE
Compatible mod, No available surface indexes.

### ISSUE THREAD

**Issue by noob117** [MagmaMcFry/Factorissimo#23]
Running Factorio 0.14.22 Build 25342
Facorissimo 0.2.0
Creative Mode 0.2.6

Have 54 factories in the world. Tried turning Creative mode on or off.
As soon as a factory is placed the following error occurs.

Error while running event on_built_entity (ID 6)
No available surface indexes.
stack traceback:
	__Factorissimo__/control.lua:40: in function 'create_surface'
	__Factorissimo__/control.lua:245: in function 'on_built_factory'
	__Factorissimo__/control.lua:272: in function <__Factorissimo__/control.lua:269>

Please let me know what information is needed.

**Comment by noob117** [comment]
Started a new map, and could not reproduce the error.

**Comment by MagmaMcFry** [comment]
I have reason to assume you've placed and destroyed about 200 other factories over the course of your save, because otherwise you wouldn't have run out of surfaces. Placing a new factory uses up one of the 256 available surfaces (that limit is hardcoded in Factorio), and destroying the factory doesn't free it up again. So this means that unfortunately you can't have more than 255 different factories ever in a single world.

Factorissimo 2 (a total rewrite, still incomplete and unreleased though) does not have this issue anymore, so you may look forward to that.

**Comment by noob117** [comment]
Yay, I can confirm that is exactly the problem I had. Thanks Magma, appreciate your work.
