### ISSUE TITLE
Crash upon placing blueprint containing factory

### ISSUE THREAD

**Issue by adamcharnock** [MagmaMcFry/Factorissimo#8]
I just installed the mod and wanted to check that I could place a blueprint of a factory. However, upon doing so the game crashes:

**Steps to recreate:**
1. Factorio version 0.13.17
2. Factorissimo 0.1.7 (no other mods)
3. Place a factory containing some blue conveyor
4. Create a blueprint containing it
5. Place the blueprint

**Expected result:** A new factory is created containing a copy of the blue conveyor

**Actual result:** Game crashes during factory construction process (It crashed once after the factory was placed, but before the belt was placed. It crashed again before the factory was placed)

**Error log:** https://gist.github.com/adamcharnock/9c8e5dcc5c07a60b879871987d73f7b7

**Save game:** https://dl.dropboxusercontent.com/u/41936/Factorissimo%20Bug%20Report.zip

(Note, the save game has the blueprint ready to place in slot 2. Save game is still uploading due to slow connection here)

**Comment by MagmaMcFry** [comment]
I am aware of the crash issue, I think it appeared in the latest update. Blueprints do not save the contents of factory interiors and probably never will. If you want to duplicate factories, you need to blueprint and rebuild the interiors separately. The mod isn't particularly robot-friendly, I know.

I'll find a fix for the crash. In the meantime, if you want to copy-paste layouts that include factories, you need to remove the factories from the blueprint (you can do that in blueprint edit mode, no need to pick up the factories), and place the factories manually instead.

**Comment by adamcharnock** [comment]
Thank you @MagmaMcFry, thank you for the explanation! Also, I love the mod! 💃

**Comment by Olipro** [comment]
I haven't currently got enough time to devote to contributing, so I'll just leave this suggestion:

Rather than using the health value hack, why not save all factory layouts entirely decoupled from the factory entity object itself and present the user with a selection panel whenever they place a factory (if there are any pending/saved ones)

You could then extend that so that users can prototype factories - naturally with a check to determine whether the player needs to "pay" for the inside entities or is "owed" them as a result of demolishing a previous factory.
